### ISSUE TITLE
Error when using accessing declared attributes of Predicate subclasses on python 3.14.3

### ISSUE THREAD

**Issue by namcsi** [potassco/clorm#144]
Hey Dave! I upgraded my machine recently to run python 3.14.3. I am now getting an error message when using clorm. A copied over a minimal example that reproduces the error:
```
from clorm import Predicate, ConstantStr

class Type(Predicate):
    """
    Defines a type in the grammar.

    Args:
        name (const): The name of the type.
    """

    name: ConstantStr

Type.name
```
gives error:
```
AttributeError: type object 'Type' has no attribute 'name'
```

Downgrading back to my previous  3.13.7 python version resolves the error - so I guess the jump over to 3.14 must break something, unsure what though:)

Thanks for you work on the package!

**Comment by daveraja** [comment]
@namcsi Thanks for reporting this. I hadn't kept up with the release of Python 3.14.

It looks like Python 3.14 makes quite a lot of changes with how annotations are handled and I'll have to look into what needs to change in clorm.

As a short term fix adding:

```from __future__ import annotations```

at the top of the python files where the clorm class declarations are made seemed to work for me. But of course this is  not a solution for using an existing project so sticking to 3.13 is the best option for the moment.

**Comment by daveraja** [comment]
@namcsi I've release clorm 1.6.2 that should work with Python 3.14. Feel free to test it out and let me know if you spot any problems.
